//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBBackuperTest.BackupServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BackupServiceReference.IBackupTaskService")]
    public interface IBackupTaskService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackupTaskService/GetBackupTasks", ReplyAction="http://tempuri.org/IBackupTaskService/GetBackupTasksResponse")]
        LBCommon.BackupTaskDef[] GetBackupTasks(string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackupTaskService/GetBackupTasks", ReplyAction="http://tempuri.org/IBackupTaskService/GetBackupTasksResponse")]
        System.Threading.Tasks.Task<LBCommon.BackupTaskDef[]> GetBackupTasksAsync(string ipAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBackupTaskServiceChannel : LBBackuperTest.BackupServiceReference.IBackupTaskService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BackupTaskServiceClient : System.ServiceModel.ClientBase<LBBackuperTest.BackupServiceReference.IBackupTaskService>, LBBackuperTest.BackupServiceReference.IBackupTaskService {
        
        public BackupTaskServiceClient() {
        }
        
        public BackupTaskServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BackupTaskServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackupTaskServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackupTaskServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LBCommon.BackupTaskDef[] GetBackupTasks(string ipAddress) {
            return base.Channel.GetBackupTasks(ipAddress);
        }
        
        public System.Threading.Tasks.Task<LBCommon.BackupTaskDef[]> GetBackupTasksAsync(string ipAddress) {
            return base.Channel.GetBackupTasksAsync(ipAddress);
        }
    }
}
