//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBBackuperTest.LogServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogServiceReference.ILogService")]
    public interface ILogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogService/WriteLog", ReplyAction="http://tempuri.org/ILogService/WriteLogResponse")]
        void WriteLog(string applicationName, System.Diagnostics.EventLogEntryType messageType, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogService/WriteLog", ReplyAction="http://tempuri.org/ILogService/WriteLogResponse")]
        System.Threading.Tasks.Task WriteLogAsync(string applicationName, System.Diagnostics.EventLogEntryType messageType, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogServiceChannel : LBBackuperTest.LogServiceReference.ILogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogServiceClient : System.ServiceModel.ClientBase<LBBackuperTest.LogServiceReference.ILogService>, LBBackuperTest.LogServiceReference.ILogService {
        
        public LogServiceClient() {
        }
        
        public LogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WriteLog(string applicationName, System.Diagnostics.EventLogEntryType messageType, string message) {
            base.Channel.WriteLog(applicationName, messageType, message);
        }
        
        public System.Threading.Tasks.Task WriteLogAsync(string applicationName, System.Diagnostics.EventLogEntryType messageType, string message) {
            return base.Channel.WriteLogAsync(applicationName, messageType, message);
        }
    }
}
